version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "clarity-software"
    networks:
      - webnet
    volumes:
      - initdb:/var/lib/postgres/data
  clarity-software:
    build: .
    container_name: claritysoftware
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
    networks:
      - webnet
volumes:
  initdb:
networks:
  webnet:
    driver: bridge